apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    name: selenium-hub
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
        name: selenium-hub
        component: "selenium-grid-4"
    spec:
     containers:
       - name: selenium-hub
         image: selenium/hub:4.9.1-20230508
         env:
           - name: JAVA_OPTS
             value: "-Xmx1024m"
         ports:
           - containerPort: 4442
             protocol: TCP
           - containerPort: 4443
             protocol: TCP
           - containerPort: 4444
             protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
    component: "selenium-grid-4"
spec:
  type: ClusterIP
  selector:
    app: selenium-hub
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444