apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-service
 annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
  - host: local-testing.com
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: jenkins
          port:
           number: 8080
#      - path: /selenium/*
#        pathType: ImplementationSpecific
#        backend:
#         service:
#          name: selenium-router
#          port:
#           number: 4444
#      - path: /jenkins/*
#        pathType: ImplementationSpecific
#        backend:
#         service:
#          name: jenkins
#          port:
#           number: 8080



