apiVersion: apps/v1
kind: Deployment
metadata:
 name: selenium-node-chrome-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
   app: selenium-node-chrome
 template:
  metadata:
   name: selenium-node-chrome
   labels:
    app: selenium-node-chrome
  spec:
   containers:
    - name: selenium-node-chrome
      image: selenium/node-chrome
      ports:
       - containerPort: 5900
      env:
       - name:  HUB_HOST
         value: "selenium-service"
       - name: HUB_PORT
         value: "4444"