apiVersion: apps/v1
kind: Deployment
metadata:
 name: selenium-node-firefox-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
   app: selenium-node-firefox
 template:
  metadata:
   name: selenium-node-firefox
   labels:
    app: selenium-node-firefox
  spec:
   containers:
    - name: selenium-node-firefox
      image: selenium/node-firefox
      ports:
       - containerPort: 5900
      env:
       - name:  HUB_HOST
         value: "selenium-service"
       - name: HUB_PORT
         value: "4444"